-- Main table as customer_data
select * from customer_data limit 4;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer_data
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount  from customer_data
where discount_applied = 'Yes'
and purchase_amount > (select avg(purchase_amount) from customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as avg_review
from customer_data
group by item_purchased
order by avg_review desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as "average purchase" from customer_data
where shipping_type in ('Express', 'Standard')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, round(avg(purchase_amount),2) as "Average Purchase", sum(purchase_amount) as "Total Revenue"
from customer_data group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased as product,
round((sum(case 
	 when discount_applied = 'Yes' then 1
	 else 0 end
	)* 100.0 /count(item_purchased)),2)  as "sales percentage with discount"
from customer_data
group by item_purchased
order by "sales percentage with discount" desc limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with CTE as (
	select *,
	(
	 case when previous_purchases =1 then 'New'
	 	  when previous_purchases <=10 then 'Returning'
		  else 'Loyal' end
	) as segment
	from customer_data
)

select Segment,
count(*) as "No of customers"
from CTE group by Segment


--Q8. What are the top 3 most purchased products within each category?
with CTE as (
	select category, item_purchased, count(*) as quantity_sold,
	row_number() over(partition by category order by count(*) desc) as rn
	from customer_data
	group by category, item_purchased
)
select category, item_purchased as Top_3_products, quantity_sold from CTE
where rn <= 3
order by category;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, round(count(*)*100.0/(select count(*) from customer_data),2) as customer_percentage
from customer_data
where previous_purchases >= 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as Total_contribution
from customer_data
group by age_group
order by Total_contribution desc






